sudo: false
language: php
php:
  - '7.0'
  - '5.6'
  - '5.5'
  - '5.4'
  - '5.3'
notifications:
  on_success: never
  on_failure: never
before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
script:
  - phpunit
env:
  matrix:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=4.5 WP_MULTISITE=0
    - WP_VERSION=4.4 WP_MULTISITE=0
    - WP_VERSION=4.3 WP_MULTISITE=0
    - WP_VERSION=4.2 WP_MULTISITE=0
    - WP_VERSION=4.1 WP_MULTISITE=0
    - WP_VERSION=4.0 WP_MULTISITE=0
    - WP_VERSION=3.9 WP_MULTISITE=0
    - WP_VERSION=3.8 WP_MULTISITE=0
    - WP_VERSION=3.7 WP_MULTISITE=0
